# Generated by Django 2.0.1 on 2018-01-26 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marks',
            name='T_marks',
            field=models.CharField(max_length=20),
        ),
    ]
