# Generated by Django 2.0.1 on 2018-01-26 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_auto_20180126_1831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marks',
            name='T_marks',
            field=models.FloatField(),
        ),
    ]
