# Generated by Django 2.0.1 on 2018-01-27 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_auto_20180126_1833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subwise_marks',
            name='Marks',
            field=models.FloatField(default=0.0),
        ),
    ]
