# Generated by Django 2.0.1 on 2018-01-27 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_auto_20180127_1122'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='C_name',
            new_name='cname',
        ),
        migrations.RenameField(
            model_name='faculty',
            old_name='D_name',
            new_name='dname',
        ),
        migrations.RenameField(
            model_name='marks',
            old_name='Grade',
            new_name='grade',
        ),
        migrations.RenameField(
            model_name='marks',
            old_name='T_marks',
            new_name='tmarks',
        ),
    ]
