# Generated by Django 2.0.1 on 2018-01-27 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_auto_20180127_1432'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='subwise_marks',
            unique_together={('EnrollmentID', 'C_ID')},
        ),
    ]
