# Generated by Django 2.0.1 on 2018-01-28 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_auto_20180127_2323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subwise_marks',
            name='Marks',
            field=models.FloatField(),
        ),
    ]
