# Generated by Django 2.0.1 on 2018-01-28 08:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0008_auto_20180128_1320'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student_course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('C_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.Course')),
                ('EnrollmentID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.Post')),
            ],
        ),
        migrations.AlterField(
            model_name='subwise_marks',
            name='Marks',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
    ]
