# Generated by Django 2.0.1 on 2018-01-28 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0009_auto_20180128_1332'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student_course',
            name='C_ID',
        ),
        migrations.RemoveField(
            model_name='student_course',
            name='EnrollmentID',
        ),
        migrations.DeleteModel(
            name='Student_course',
        ),
    ]
